# Generated by Django 2.2.16 on 2020-11-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('name', models.CharField(choices=[('HuangYanYan', '黄烟烟'), ('YaoBuRan', '药不然'), ('JiYunFu', '姬云浮'), ('XuYuan', '许愿'), ('LaoChaoFeng', '老朝奉'), ('ZhengGuoQu', '郑国渠'), ('Kana Kinoshi', '木户加奈'), ('FangZhen', '方震')], max_length=31, unique=True)),
                ('skill_description', models.CharField(max_length=1023, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('room_id', models.PositiveSmallIntegerField(help_text='Room Number', unique=True, verbose_name='Room ID')),
                ('stage', models.PositiveSmallIntegerField(default=0)),
                ('start_color_index', models.PositiveSmallIntegerField()),
                ('characters', models.ManyToManyField(blank=True, to='GameMaster.Character')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('name', models.CharField(max_length=255)),
                ('player_code', models.PositiveSmallIntegerField(help_text='Player Code', unique=True, verbose_name='Player Code')),
                ('color', models.CharField(choices=[('White', '白'), ('Green', '绿'), ('Yellow', '黄'), ('Blue', '蓝'), ('Black', '黑'), ('Purple', '紫'), ('Orange', '橙'), ('Red', '红')], max_length=7, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=999)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GameMaster.Character', verbose_name='Character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='GameMaster.Game')),
            ],
            options={
                'ordering': ['game', 'color'],
                'unique_together': {('game', 'character'), ('game', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ZodiacImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('name', models.CharField(choices=[('Rat', '鼠'), ('Monkey', '猴'), ('Tiger', '虎'), ('Rooster', '鸡'), ('Snake', '蛇'), ('Dragon', '龙'), ('Horse', '马'), ('Rabbit', '兔'), ('Dog', '狗'), ('Pig', '猪'), ('Sheep', '羊'), ('Ox', '牛')], max_length=31, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='Images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('name', models.CharField(choices=[('Rat', '鼠'), ('Monkey', '猴'), ('Tiger', '虎'), ('Rooster', '鸡'), ('Snake', '蛇'), ('Dragon', '龙'), ('Horse', '马'), ('Rabbit', '兔'), ('Dog', '狗'), ('Pig', '猪'), ('Sheep', '羊'), ('Ox', '牛')], max_length=31)),
                ('genuine', models.BooleanField(default=True, verbose_name='真伪')),
                ('sequence', models.PositiveSmallIntegerField(null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Inverted'), (2, 'Blocked'), (0, 'Normal')], default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zodiacs', to='GameMaster.Game')),
                ('zodiac_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zodiacs', to='GameMaster.ZodiacImage', verbose_name='Zodiac Image')),
            ],
            options={
                'ordering': ['game', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('skill_used', models.BooleanField(null=True)),
                ('game_progress', models.PositiveSmallIntegerField(default=-1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='GameMaster.Character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='GameMaster.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='GameMaster.Player')),
                ('zodic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='GameMaster.Zodiac')),
            ],
            options={
                'ordering': ['game', 'game_progress'],
            },
        ),
    ]
