# Generated by Django 2.2.16 on 2020-11-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zodiacimage',
            name='image',
        ),
        migrations.AddField(
            model_name='zodiacimage',
            name='image_url',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('YaoBuRan', '药不然'), ('XuYuan', '许愿'), ('FangZhen', '方震'), ('JiYunFu', '姬云浮'), ('LaoChaoFeng', '老朝奉'), ('Kana Kinoshi', '木户加奈'), ('ZhengGuoQu', '郑国渠'), ('HuangYanYan', '黄烟烟')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Blue', '蓝'), ('White', '白'), ('Yellow', '黄'), ('Purple', '紫'), ('Green', '绿'), ('Black', '黑'), ('Orange', '橙'), ('Red', '红')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Pig', '猪'), ('Tiger', '虎'), ('Rabbit', '兔'), ('Snake', '蛇'), ('Rooster', '鸡'), ('Rat', '鼠'), ('Monkey', '猴'), ('Horse', '马'), ('Dog', '狗'), ('Sheep', '羊'), ('Ox', '牛'), ('Dragon', '龙')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Pig', '猪'), ('Tiger', '虎'), ('Rabbit', '兔'), ('Snake', '蛇'), ('Rooster', '鸡'), ('Rat', '鼠'), ('Monkey', '猴'), ('Horse', '马'), ('Dog', '狗'), ('Sheep', '羊'), ('Ox', '牛'), ('Dragon', '龙')], max_length=31, unique=True),
        ),
    ]
