# Generated by Django 2.2.16 on 2020-11-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster', '0002_auto_20201113_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('FangZhen', '方震'), ('HuangYanYan', '黄烟烟'), ('JiYunFu', '姬云浮'), ('ZhengGuoQu', '郑国渠'), ('Kana Kinoshi', '木户加奈'), ('XuYuan', '许愿'), ('YaoBuRan', '药不然'), ('LaoChaoFeng', '老朝奉')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Black', '黑'), ('Green', '绿'), ('Red', '红'), ('Orange', '橙'), ('Blue', '蓝'), ('Yellow', '黄'), ('White', '白'), ('Purple', '紫')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Monkey', '猴'), ('Tiger', '虎'), ('Rat', '鼠'), ('Ox', '牛'), ('Pig', '猪'), ('Sheep', '羊'), ('Dog', '狗'), ('Dragon', '龙'), ('Snake', '蛇'), ('Rabbit', '兔'), ('Rooster', '鸡'), ('Horse', '马')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inverted'), (0, 'Normal'), (2, 'Blocked')], default=0),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='image_url',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Monkey', '猴'), ('Tiger', '虎'), ('Rat', '鼠'), ('Ox', '牛'), ('Pig', '猪'), ('Sheep', '羊'), ('Dog', '狗'), ('Dragon', '龙'), ('Snake', '蛇'), ('Rabbit', '兔'), ('Rooster', '鸡'), ('Horse', '马')], max_length=31, unique=True),
        ),
    ]
