# Generated by Django 2.2.16 on 2020-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster', '0003_auto_20201113_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='characters',
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('JiYunFu', '姬云浮'), ('YaoBuRan', '药不然'), ('FangZhen', '方震'), ('XuYuan', '许愿'), ('ZhengGuoQu', '郑国渠'), ('HuangYanYan', '黄烟烟'), ('LaoChaoFeng', '老朝奉'), ('Kana Kinoshi', '木户加奈')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('White', '白'), ('Orange', '橙'), ('Green', '绿'), ('Purple', '紫'), ('Red', '红'), ('Black', '黑'), ('Blue', '蓝'), ('Yellow', '黄')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Pig', '猪'), ('Ox', '牛'), ('Horse', '马'), ('Rooster', '鸡'), ('Tiger', '虎'), ('Sheep', '羊'), ('Dragon', '龙'), ('Snake', '蛇'), ('Monkey', '猴'), ('Rabbit', '兔'), ('Dog', '狗'), ('Rat', '鼠')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Pig', '猪'), ('Ox', '牛'), ('Horse', '马'), ('Rooster', '鸡'), ('Tiger', '虎'), ('Sheep', '羊'), ('Dragon', '龙'), ('Snake', '蛇'), ('Monkey', '猴'), ('Rabbit', '兔'), ('Dog', '狗'), ('Rat', '鼠')], max_length=31, unique=True),
        ),
    ]
