# Generated by Django 2.2.16 on 2020-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMaster', '0004_auto_20201113_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('JiYunFu', '姬云浮'), ('XuYuan', '许愿'), ('HuangYanYan', '黄烟烟'), ('ZhengGuoQu', '郑国渠'), ('FangZhen', '方震'), ('Kana Kinoshi', '木户加奈'), ('YaoBuRan', '药不然'), ('LaoChaoFeng', '老朝奉')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Orange', '橙'), ('Blue', '蓝'), ('Yellow', '黄'), ('White', '白'), ('Purple', '紫'), ('Black', '黑'), ('Red', '红'), ('Green', '绿')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Rabbit', '兔'), ('Dragon', '龙'), ('Monkey', '猴'), ('Snake', '蛇'), ('Tiger', '虎'), ('Rooster', '鸡'), ('Sheep', '羊'), ('Pig', '猪'), ('Rat', '鼠'), ('Dog', '狗'), ('Horse', '马'), ('Ox', '牛')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (2, 'Blocked'), (1, 'Inverted')], default=0),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Rabbit', '兔'), ('Dragon', '龙'), ('Monkey', '猴'), ('Snake', '蛇'), ('Tiger', '虎'), ('Rooster', '鸡'), ('Sheep', '羊'), ('Pig', '猪'), ('Rat', '鼠'), ('Dog', '狗'), ('Horse', '马'), ('Ox', '牛')], max_length=31, unique=True),
        ),
    ]
