# Generated by Django 2.1.4 on 2018-12-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveSmallIntegerField(help_text='Room Number', max_length=6, unique=True, verbose_name='Room ID')),
                ('stage', models.PositiveSmallIntegerField(default=0, max_length=1, verbose_name='Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_code', models.PositiveSmallIntegerField(help_text='Player Code', max_length=3, unique=True, verbose_name='Player Code')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MoA.Game', verbose_name='Game')),
            ],
        ),
    ]
