# Generated by Django 2.1.4 on 2018-12-18 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0003_auto_20181218_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, to='MoA.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='MoA.Character', verbose_name='Character'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('FanZhen', '方震'), ('ZhengGuoQu', '郑国渠'), ('HuanYanYan', '黄烟烟'), ('Kana Kinoshi', '木户加奈'), ('LaoChaoFeng', '老朝奉'), ('XuYuan', '许愿'), ('JiYunFu', '姬云浮'), ('YaoBuRan', '药不然')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='MoA.Game', verbose_name='Game'),
        ),
    ]
