# Generated by Django 2.1.4 on 2018-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0005_auto_20181218_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_description',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('JiYunFu', '姬云浮'), ('YaoBuRan', '药不然'), ('ZhengGuoQu', '郑国渠'), ('LaoChaoFeng', '老朝奉'), ('HuanYanYan', '黄烟烟'), ('Kana Kinoshi', '木户加奈'), ('XuYuan', '许愿'), ('FanZhen', '方震')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(blank=True, to='MoA.Character'),
        ),
    ]
