# Generated by Django 2.1.4 on 2018-12-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0006_auto_20181218_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('White', '白'), ('Orange', '橙'), ('Blue', '蓝'), ('Green', '绿'), ('Black', '黑'), ('Yellow', '黄'), ('Red', '红'), ('Purple', '紫')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('JiYunFu', '姬云浮'), ('Kana Kinoshi', '木户加奈'), ('HuanYanYan', '黄烟烟'), ('YaoBuRan', '药不然'), ('FanZhen', '方震'), ('XuYuan', '许愿'), ('ZhengGuoQu', '郑国渠'), ('LaoChaoFeng', '老朝奉')], max_length=31, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'character'), ('game', 'color')},
        ),
    ]
