# Generated by Django 2.1.4 on 2018-12-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0008_auto_20181218_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='isAlive',
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('LaoChaoFeng', '老朝奉'), ('Kana Kinoshi', '木户加奈'), ('FanZhen', '方震'), ('YaoBuRan', '药不然'), ('ZhengGuoQu', '郑国渠'), ('JiYunFu', '姬云浮'), ('XuYuan', '许愿'), ('HuanYanYan', '黄烟烟')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Yellow', '黄'), ('Red', '红'), ('Orange', '橙'), ('Green', '绿'), ('Blue', '蓝'), ('Purple', '紫'), ('Black', '黑'), ('White', '白')], max_length=7, null=True),
        ),
    ]
