# Generated by Django 2.1.4 on 2018-12-19 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoA', '0010_auto_20181219_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Dragon', '龙'), ('Ox', '牛'), ('Monkey', '猴'), ('Rooster', '鸡'), ('Horse', '马'), ('Pig', '猪'), ('Sheep', '羊'), ('Dog', '狗'), ('Tiger', '虎'), ('Snake', '蛇'), ('Rat', '鼠'), ('Rabbit', '兔')], max_length=31)),
                ('image', models.FileField(blank=True, null=True, upload_to='Images/')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_zodiacimage_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text='Who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_zodiacimage_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='zodiac',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='zodiacs', to='MoA.Game', verbose_name='Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zodiac',
            name='genuine',
            field=models.BooleanField(default=True, verbose_name='真伪'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('JiYunFu', '姬云浮'), ('FanZhen', '方震'), ('HuanYanYan', '黄烟烟'), ('YaoBuRan', '药不然'), ('XuYuan', '许愿'), ('ZhengGuoQu', '郑国渠'), ('LaoChaoFeng', '老朝奉'), ('Kana Kinoshi', '木户加奈')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Black', '黑'), ('Orange', '橙'), ('White', '白'), ('Green', '绿'), ('Yellow', '黄'), ('Red', '红'), ('Blue', '蓝'), ('Purple', '紫')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Dragon', '龙'), ('Ox', '牛'), ('Monkey', '猴'), ('Rooster', '鸡'), ('Horse', '马'), ('Pig', '猪'), ('Sheep', '羊'), ('Dog', '狗'), ('Tiger', '虎'), ('Snake', '蛇'), ('Rat', '鼠'), ('Rabbit', '兔')], max_length=31),
        ),
        migrations.AddField(
            model_name='zodiac',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='zodiacs', to='MoA.ZodiacImage', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
