# Generated by Django 2.1.4 on 2018-12-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0012_auto_20181219_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_color',
            field=models.CharField(choices=[('Red', '红'), ('Green', '绿'), ('Yellow', '黄'), ('White', '白'), ('Blue', '蓝'), ('Black', '黑'), ('Orange', '橙'), ('Purple', '紫')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('LaoChaoFeng', '老朝奉'), ('JiYunFu', '姬云浮'), ('XuYuan', '许愿'), ('YaoBuRan', '药不然'), ('FanZhen', '方震'), ('HuanYanYan', '黄烟烟'), ('Kana Kinoshi', '木户加奈'), ('ZhengGuoQu', '郑国渠')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Red', '红'), ('Green', '绿'), ('Yellow', '黄'), ('White', '白'), ('Blue', '蓝'), ('Black', '黑'), ('Orange', '橙'), ('Purple', '紫')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Dragon', '龙'), ('Snake', '蛇'), ('Ox', '牛'), ('Sheep', '羊'), ('Horse', '马'), ('Pig', '猪'), ('Rabbit', '兔'), ('Rat', '鼠'), ('Monkey', '猴'), ('Rooster', '鸡'), ('Dog', '狗'), ('Tiger', '虎')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Dragon', '龙'), ('Snake', '蛇'), ('Ox', '牛'), ('Sheep', '羊'), ('Horse', '马'), ('Pig', '猪'), ('Rabbit', '兔'), ('Rat', '鼠'), ('Monkey', '猴'), ('Rooster', '鸡'), ('Dog', '狗'), ('Tiger', '虎')], max_length=31, unique=True),
        ),
    ]
