# Generated by Django 2.1.4 on 2018-12-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0013_auto_20181219_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='start_color',
        ),
        migrations.AddField(
            model_name='game',
            name='start_color_index',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('XuYuan', '许愿'), ('JiYunFu', '姬云浮'), ('HuanYanYan', '黄烟烟'), ('LaoChaoFeng', '老朝奉'), ('Kana Kinoshi', '木户加奈'), ('FanZhen', '方震'), ('YaoBuRan', '药不然'), ('ZhengGuoQu', '郑国渠')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Yellow', '黄'), ('Blue', '蓝'), ('Orange', '橙'), ('Black', '黑'), ('Red', '红'), ('Purple', '紫'), ('Green', '绿'), ('White', '白')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Sheep', '羊'), ('Tiger', '虎'), ('Snake', '蛇'), ('Horse', '马'), ('Rat', '鼠'), ('Dog', '狗'), ('Monkey', '猴'), ('Pig', '猪'), ('Dragon', '龙'), ('Ox', '牛'), ('Rooster', '鸡'), ('Rabbit', '兔')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Sheep', '羊'), ('Tiger', '虎'), ('Snake', '蛇'), ('Horse', '马'), ('Rat', '鼠'), ('Dog', '狗'), ('Monkey', '猴'), ('Pig', '猪'), ('Dragon', '龙'), ('Ox', '牛'), ('Rooster', '鸡'), ('Rabbit', '兔')], max_length=31, unique=True),
        ),
    ]
