# Generated by Django 2.1.4 on 2018-12-20 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoA', '0016_auto_20181219_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_playeraction_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text='Who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_playeraction_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='player',
            name='step',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('JiYunFu', '姬云浮'), ('XuYuan', '许愿'), ('HuanYanYan', '黄烟烟'), ('LaoChaoFeng', '老朝奉'), ('YaoBuRan', '药不然'), ('Kana Kinoshi', '木户加奈'), ('ZhengGuoQu', '郑国渠'), ('FanZhen', '方震')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Purple', '紫'), ('White', '白'), ('Black', '黑'), ('Red', '红'), ('Green', '绿'), ('Orange', '橙'), ('Yellow', '黄'), ('Blue', '蓝')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Dragon', '龙'), ('Horse', '马'), ('Ox', '牛'), ('Dog', '狗'), ('Pig', '猪'), ('Rabbit', '兔'), ('Snake', '蛇'), ('Monkey', '猴'), ('Rooster', '鸡'), ('Tiger', '虎'), ('Rat', '鼠'), ('Sheep', '羊')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Dragon', '龙'), ('Horse', '马'), ('Ox', '牛'), ('Dog', '狗'), ('Pig', '猪'), ('Rabbit', '兔'), ('Snake', '蛇'), ('Monkey', '猴'), ('Rooster', '鸡'), ('Tiger', '虎'), ('Rat', '鼠'), ('Sheep', '羊')], max_length=31, unique=True),
        ),
        migrations.AddField(
            model_name='playeraction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='MoA.Player', verbose_name='PlayerAction'),
        ),
    ]
