# Generated by Django 2.1.4 on 2018-12-20 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0017_auto_20181220_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeraction',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='MoA.Character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playeraction',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='MoA.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playeraction',
            name='skill_used',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='playeraction',
            name='zodic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='MoA.Zodiac'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('HuanYanYan', '黄烟烟'), ('XuYuan', '许愿'), ('Kana Kinoshi', '木户加奈'), ('YaoBuRan', '药不然'), ('LaoChaoFeng', '老朝奉'), ('JiYunFu', '姬云浮'), ('FanZhen', '方震'), ('ZhengGuoQu', '郑国渠')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Yellow', '黄'), ('Green', '绿'), ('Orange', '橙'), ('White', '白'), ('Black', '黑'), ('Red', '红'), ('Blue', '蓝'), ('Purple', '紫')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='MoA.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playeraction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='MoA.Player'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zodiacs', to='MoA.Game'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Rooster', '鸡'), ('Dog', '狗'), ('Rabbit', '兔'), ('Snake', '蛇'), ('Rat', '鼠'), ('Dragon', '龙'), ('Horse', '马'), ('Pig', '猪'), ('Sheep', '羊'), ('Ox', '牛'), ('Tiger', '虎'), ('Monkey', '猴')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='zodiac_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zodiacs', to='MoA.ZodiacImage', verbose_name='Zodiac Image'),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Rooster', '鸡'), ('Dog', '狗'), ('Rabbit', '兔'), ('Snake', '蛇'), ('Rat', '鼠'), ('Dragon', '龙'), ('Horse', '马'), ('Pig', '猪'), ('Sheep', '羊'), ('Ox', '牛'), ('Tiger', '虎'), ('Monkey', '猴')], max_length=31, unique=True),
        ),
    ]
