# Generated by Django 2.1.4 on 2018-12-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0019_auto_20181220_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiac',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blocked'), (0, 'Inverted'), (0, 'Normal')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('YaoBuRan', '药不然'), ('JiYunFu', '姬云浮'), ('FanZhen', '方震'), ('Kana Kinoshi', '木户加奈'), ('LaoChaoFeng', '老朝奉'), ('XuYuan', '许愿'), ('ZhengGuoQu', '郑国渠'), ('HuangYanYan', '黄烟烟')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Blue', '蓝'), ('Yellow', '黄'), ('Orange', '橙'), ('Purple', '紫'), ('Red', '红'), ('Green', '绿'), ('White', '白'), ('Black', '黑')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='MoA.Game'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zodiacs', to='MoA.Game'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Rat', '鼠'), ('Tiger', '虎'), ('Snake', '蛇'), ('Pig', '猪'), ('Horse', '马'), ('Rabbit', '兔'), ('Dog', '狗'), ('Sheep', '羊'), ('Dragon', '龙'), ('Rooster', '鸡'), ('Monkey', '猴'), ('Ox', '牛')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Rat', '鼠'), ('Tiger', '虎'), ('Snake', '蛇'), ('Pig', '猪'), ('Horse', '马'), ('Rabbit', '兔'), ('Dog', '狗'), ('Sheep', '羊'), ('Dragon', '龙'), ('Rooster', '鸡'), ('Monkey', '猴'), ('Ox', '牛')], max_length=31, unique=True),
        ),
    ]
