# Generated by Django 2.1.4 on 2018-12-18 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoA', '0002_auto_20181217_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[(5, '黄烟烟'), (6, '老朝奉'), (7, '药不然'), (8, '郑国渠'), (4, '木户加奈'), (3, '姬云浮'), (1, '许愿'), (2, '方震')], max_length=31)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_character_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text='Who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_character_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_game_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_game_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_player_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_player_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
