# Generated by Django 2.1.4 on 2018-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0004_auto_20181218_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, to='MoA.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('YaoBuRan', '药不然'), ('HuanYanYan', '黄烟烟'), ('JiYunFu', '姬云浮'), ('Kana Kinoshi', '木户加奈'), ('LaoChaoFeng', '老朝奉'), ('FanZhen', '方震'), ('ZhengGuoQu', '郑国渠'), ('XuYuan', '许愿')], max_length=31, unique=True),
        ),
    ]
