# Generated by Django 2.1.4 on 2018-12-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0007_auto_20181218_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isAlive',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('FanZhen', '方震'), ('ZhengGuoQu', '郑国渠'), ('HuanYanYan', '黄烟烟'), ('Kana Kinoshi', '木户加奈'), ('JiYunFu', '姬云浮'), ('LaoChaoFeng', '老朝奉'), ('XuYuan', '许愿'), ('YaoBuRan', '药不然')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Black', '黑'), ('Blue', '蓝'), ('Purple', '紫'), ('Green', '绿'), ('Orange', '橙'), ('Yellow', '黄'), ('Red', '红'), ('White', '白')], max_length=7, null=True),
        ),
    ]
