# Generated by Django 2.1.4 on 2018-12-19 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoA', '0009_auto_20181218_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Pig', '猪'), ('Monkey', '猴'), ('Snake', '蛇'), ('Sheep', '羊'), ('Horse', '马'), ('Dragon', '龙'), ('Rooster', '鸡'), ('Dog', '狗'), ('Rat', '鼠'), ('Ox', '牛'), ('Rabbit', '兔'), ('Tiger', '虎')], max_length=31, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_zodiac_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text='Who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moa_zodiac_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('Kana Kinoshi', '木户加奈'), ('XuYuan', '许愿'), ('YaoBuRan', '药不然'), ('HuanYanYan', '黄烟烟'), ('FanZhen', '方震'), ('LaoChaoFeng', '老朝奉'), ('JiYunFu', '姬云浮'), ('ZhengGuoQu', '郑国渠')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('White', '白'), ('Orange', '橙'), ('Green', '绿'), ('Black', '黑'), ('Blue', '蓝'), ('Red', '红'), ('Purple', '紫'), ('Yellow', '黄')], max_length=7, null=True),
        ),
    ]
