# Generated by Django 2.1.4 on 2018-12-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0014_auto_20181219_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sequence',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('JiYunFu', '姬云浮'), ('Kana Kinoshi', '木户加奈'), ('LaoChaoFeng', '老朝奉'), ('HuanYanYan', '黄烟烟'), ('YaoBuRan', '药不然'), ('ZhengGuoQu', '郑国渠'), ('XuYuan', '许愿'), ('FanZhen', '方震')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_color_index',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Black', '黑'), ('Green', '绿'), ('Orange', '橙'), ('Blue', '蓝'), ('Red', '红'), ('White', '白'), ('Purple', '紫'), ('Yellow', '黄')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Sheep', '羊'), ('Snake', '蛇'), ('Dragon', '龙'), ('Horse', '马'), ('Rat', '鼠'), ('Rabbit', '兔'), ('Ox', '牛'), ('Monkey', '猴'), ('Tiger', '虎'), ('Dog', '狗'), ('Rooster', '鸡'), ('Pig', '猪')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Sheep', '羊'), ('Snake', '蛇'), ('Dragon', '龙'), ('Horse', '马'), ('Rat', '鼠'), ('Rabbit', '兔'), ('Ox', '牛'), ('Monkey', '猴'), ('Tiger', '虎'), ('Dog', '狗'), ('Rooster', '鸡'), ('Pig', '猪')], max_length=31, unique=True),
        ),
    ]
