# Generated by Django 2.1.4 on 2018-12-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0015_auto_20181219_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('HuanYanYan', '黄烟烟'), ('XuYuan', '许愿'), ('ZhengGuoQu', '郑国渠'), ('JiYunFu', '姬云浮'), ('FanZhen', '方震'), ('Kana Kinoshi', '木户加奈'), ('YaoBuRan', '药不然'), ('LaoChaoFeng', '老朝奉')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Red', '红'), ('Blue', '蓝'), ('White', '白'), ('Purple', '紫'), ('Black', '黑'), ('Orange', '橙'), ('Yellow', '黄'), ('Green', '绿')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Monkey', '猴'), ('Tiger', '虎'), ('Snake', '蛇'), ('Ox', '牛'), ('Dragon', '龙'), ('Dog', '狗'), ('Pig', '猪'), ('Rabbit', '兔'), ('Rooster', '鸡'), ('Rat', '鼠'), ('Horse', '马'), ('Sheep', '羊')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Monkey', '猴'), ('Tiger', '虎'), ('Snake', '蛇'), ('Ox', '牛'), ('Dragon', '龙'), ('Dog', '狗'), ('Pig', '猪'), ('Rabbit', '兔'), ('Rooster', '鸡'), ('Rat', '鼠'), ('Horse', '马'), ('Sheep', '羊')], max_length=31, unique=True),
        ),
    ]
