# Generated by Django 2.1.4 on 2018-12-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0018_auto_20181220_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zodiac',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='zodiac',
            name='sequence',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('YaoBuRan', '药不然'), ('FanZhen', '方震'), ('JiYunFu', '姬云浮'), ('XuYuan', '许愿'), ('LaoChaoFeng', '老朝奉'), ('Kana Kinoshi', '木户加奈'), ('ZhengGuoQu', '郑国渠'), ('HuanYanYan', '黄烟烟')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('White', '白'), ('Orange', '橙'), ('Purple', '紫'), ('Red', '红'), ('Green', '绿'), ('Blue', '蓝'), ('Black', '黑'), ('Yellow', '黄')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Rat', '鼠'), ('Rooster', '鸡'), ('Monkey', '猴'), ('Dog', '狗'), ('Dragon', '龙'), ('Ox', '牛'), ('Horse', '马'), ('Tiger', '虎'), ('Rabbit', '兔'), ('Snake', '蛇'), ('Pig', '猪'), ('Sheep', '羊')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Rat', '鼠'), ('Rooster', '鸡'), ('Monkey', '猴'), ('Dog', '狗'), ('Dragon', '龙'), ('Ox', '牛'), ('Horse', '马'), ('Tiger', '虎'), ('Rabbit', '兔'), ('Snake', '蛇'), ('Pig', '猪'), ('Sheep', '羊')], max_length=31, unique=True),
        ),
    ]
