# Generated by Django 2.1.4 on 2018-12-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoA', '0020_auto_20181221_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['game', 'color']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='game',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='player',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='player',
            name='step',
        ),
        migrations.RemoveField(
            model_name='playeraction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='playeraction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='zodiac',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='zodiac',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='zodiacimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='zodiacimage',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='player',
            name='endBB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='skill_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('LaoChaoFeng', '老朝奉'), ('XuYuan', '许愿'), ('YaoBuRan', '药不然'), ('FanZhen', '方震'), ('JiYunFu', '姬云浮'), ('Kana Kinoshi', '木户加奈'), ('ZhengGuoQu', '郑国渠'), ('HuangYanYan', '黄烟烟')], max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('Purple', '紫'), ('Orange', '橙'), ('Yellow', '黄'), ('Black', '黑'), ('Green', '绿'), ('White', '白'), ('Blue', '蓝'), ('Red', '红')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('Rabbit', '兔'), ('Ox', '牛'), ('Dragon', '龙'), ('Rooster', '鸡'), ('Pig', '猪'), ('Rat', '鼠'), ('Horse', '马'), ('Sheep', '羊'), ('Dog', '狗'), ('Tiger', '虎'), ('Monkey', '猴'), ('Snake', '蛇')], max_length=31),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (0, 'Blocked'), (0, 'Inverted')], default=0),
        ),
        migrations.AlterField(
            model_name='zodiacimage',
            name='name',
            field=models.CharField(choices=[('Rabbit', '兔'), ('Ox', '牛'), ('Dragon', '龙'), ('Rooster', '鸡'), ('Pig', '猪'), ('Rat', '鼠'), ('Horse', '马'), ('Sheep', '羊'), ('Dog', '狗'), ('Tiger', '虎'), ('Monkey', '猴'), ('Snake', '蛇')], max_length=31, unique=True),
        ),
    ]
